/**
 * Shrimp Farm Application
 * Service Contract
 *
 * OpenAPI spec version: 1.0.0
 * Contact: patti_gm2010@live.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Pond } from './pond';


export class Farm { 
    id?: string;
    name?: string;
    totalSize?: number;
    nameLocation?: string;
    latitude?: number= 0;
    longitude?: number= 0;
    ponds?: Array<Pond>;
}
