/**
 * Shrimp Farm Application
 * Service Contract
 *
 * OpenAPI spec version: 1.0.0
 * Contact: patti_gm2010@live.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Pond { 
    id?: string;
    name?: string;
    size?: number;
}
