/**
 * Shrimp Farm Application
 * Service Contract
 *
 * OpenAPI spec version: 1.0.0
 * Contact: patti_gm2010@live.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../api/encoder';

import { Observable }                                        from 'rxjs';

import { ApiResponse } from '../model/apiResponse';
import { Pond } from '../model/pond';

import { BASE_PATH }                     from '../api/variables';
import { Configuration }                                     from '../api/configuration';


@Injectable()
export class PondService {

    protected basePath = 'http://localhost:9000/sfarm/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Management of ponds
     * 
     * @param idFarm Id Farm
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPond(idFarm: string, body: Pond, observe?: 'body', reportProgress?: boolean): Observable<ApiResponse>;
    public createPond(idFarm: string, body: Pond, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ApiResponse>>;
    public createPond(idFarm: string, body: Pond, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ApiResponse>>;
    public createPond(idFarm: string, body: Pond, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFarm === null || idFarm === undefined) {
            throw new Error('Required parameter idFarm was null or undefined when calling createPond.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createPond.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idFarm !== undefined && idFarm !== null) {
            queryParameters = queryParameters.set('idFarm', <any>idFarm);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ApiResponse>(`${this.basePath}/pond`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a pond from database
     * 
     * @param idFarm Id Farm
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePond(idFarm: string, idPond: string, observe?: 'body', reportProgress?: boolean): Observable<ApiResponse>;
    public deletePond(idFarm: string, idPond: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ApiResponse>>;
    public deletePond(idFarm: string, idPond: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ApiResponse>>;
    public deletePond(idFarm: string, idPond: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFarm === null || idFarm === undefined) {
            throw new Error('Required parameter idFarm was null or undefined when calling deletePond.');
        }

        if (idPond === null || idPond === undefined) {
            throw new Error('Required parameter idPond was null or undefined when calling deletePond.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idFarm !== undefined && idFarm !== null) {
            queryParameters = queryParameters.set('idFarm', <any>idFarm);
        }
        if (idPond !== undefined && idPond !== null) {
            queryParameters = queryParameters.set('idPond', <any>idPond);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<ApiResponse>(`${this.basePath}/pond`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }



    /**
     * Find pond by farmid
     * 
     * @param farmId Farm´s id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPondByFarmid(farmId: string, observe?: 'body', reportProgress?: boolean): Observable<ApiResponse>;
    public getPondByFarmid(farmId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ApiResponse>>;
    public getPondByFarmid(farmId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ApiResponse>>;
    public getPondByFarmid(farmId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (farmId === null || farmId === undefined) {
            throw new Error('Required parameter farmId was null or undefined when calling getPondByFarmid.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ApiResponse>(`${this.basePath}/pond/getPondByFarmId/${encodeURIComponent(String(farmId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find farm by id
     * 
     * @param pondId Pond´s id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPondById(pondId: string, observe?: 'body', reportProgress?: boolean): Observable<ApiResponse>;
    public getPondById(pondId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ApiResponse>>;
    public getPondById(pondId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ApiResponse>>;
    public getPondById(pondId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pondId === null || pondId === undefined) {
            throw new Error('Required parameter pondId was null or undefined when calling getPondById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ApiResponse>(`${this.basePath}/pond/getPondById/${encodeURIComponent(String(pondId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update the fields of pond
     * 
     * @param idFarm Id Farm
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePond(idFarm: string, body: Pond, observe?: 'body', reportProgress?: boolean): Observable<ApiResponse>;
    public updatePond(idFarm: string, body: Pond, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ApiResponse>>;
    public updatePond(idFarm: string, body: Pond, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ApiResponse>>;
    public updatePond(idFarm: string, body: Pond, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFarm === null || idFarm === undefined) {
            throw new Error('Required parameter idFarm was null or undefined when calling updatePond.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updatePond.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idFarm !== undefined && idFarm !== null) {
            queryParameters = queryParameters.set('idFarm', <any>idFarm);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<ApiResponse>(`${this.basePath}/pond`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
